/**
 * Plays bundled WAV clips (generated by scripts/make-audio.ps1). Unlike the
 * Web Speech API, file playback works in every browser — including Chromium
 * forks that ship without TTS voices — and offline via the service worker.
 */

let current: HTMLAudioElement | null = null

export function stopFile(): void {
  if (current) {
    try {
      current.pause()
    } catch {
      // already stopped
    }
    current = null
  }
}

/** Resolves true if the clip played (or is playing), false to use a fallback. */
export function playFile(relPath: string): Promise<boolean> {
  if (typeof Audio === 'undefined') return Promise.resolve(false)
  return new Promise((resolve) => {
    stopFile()
    const el = new Audio(`${import.meta.env.BASE_URL}${relPath}`)
    current = el
    let settled = false
    const finish = (ok: boolean) => {
      if (settled) return
      settled = true
      if (current === el) current = null
      resolve(ok)
    }
    el.onended = () => finish(true)
    el.onerror = () => finish(false)
    let started: unknown
    try {
      started = el.play()
    } catch {
      finish(false)
      return
    }
    if (started && typeof (started as Promise<void>).catch === 'function') {
      ;(started as Promise<void>).catch(() => finish(false))
      // Safety net for engines that drop the ended event
      window.setTimeout(() => finish(true), 15000)
    } else {
      // Environments without real playback (e.g. jsdom in tests)
      finish(false)
    }
  })
}
